import keyMirror from 'keyMirror';

const constants = keyMirror({
	GET_STATE: null,
	GET_STATE_FAILURE: null,
	GET_STATE_SUCCESS: null,

	SELECT_TAB: null,

	SELECT_TESTS_RESULT_BY_PERIOD: null,
	SELECT_TESTS_RESULT_BY_PERIOD_FAILURE: null,
	SELECT_TESTS_RESULT_BY_PERIOD_SUCCESS: null,

	SELECT_COURSES_RESULT_BY_PERIOD: null,
	SELECT_COURSES_RESULT_BY_PERIOD_FAILURE: null,
	SELECT_COURSES_RESULT_BY_PERIOD_SUCCESS: null,

	SELECT_EVENTS_PERIOD: null,
	SELECT_EVENTS_PERIOD_FAILURE: null,
	SELECT_EVENTS_PERIOD_SUCCESS: null,

	SELECT_TESTS_RESULT: null,
	SELECT_TESTS_RESULT_FAILURE: null,
	SELECT_TESTS_RESULT_SUCCESS: null,

	SELECT_COURSES_RESULT: null,
	SELECT_COURSES_RESULT_FAILURE: null,
	SELECT_COURSES_RESULT_SUCCESS: null,

	SELECT_ADAPT_RESULT: null,
	SELECT_ADAPT_RESULT_FAILURE: null,
	SELECT_ADAPT_RESULT_SUCCESS: null,

	SELECT_REQUESTS_RESULT: null,
	SELECT_REQUESTS_RESULT_FAILURE: null,
	SELECT_REQUESTS_RESULT_SUCCESS: null,

	SELECT_LIBRARY_MATERIALS_PERIOD: null,
	SELECT_LIBRARY_MATERIALS_PERIOD_FAILURE: null,
	SELECT_LIBRARY_MATERIALS_PERIOD_SUCCESS: null
});

export default constants;